[[news]]
date = "2026-09"
content = "Started the MSc in Social Computing at Xi'an Jiaotong-Liverpool University."

[[news]]
date = "2025-06"
content = "Graduated from Northwest A&F University with a Bachelor of Management in Social Affairs Administration."
