type = "card"
title = "Academic Service"
layout = "timeline"

[[items]]
title = "Political Science Review"
subtitle = "Head of the Second Division, Chinese Academic Department"
date = "2023–Present"

[[items]]
title = "China Public Management Community"
subtitle = "Leader of the Rural Governance Group"
date = "2024–Present"
