[[news]]
date = "2026-09"
content = "开始在西交利物浦大学攻读社会网络计算技术理学硕士学位。"

[[news]]
date = "2026"
content = "获华南理工大学博学论坛优秀论文奖。"

[[news]]
date = "2025-06"
content = "毕业于西北农林科技大学公共事业管理专业；本科毕业论文获校级优秀毕业论文及百篇优秀毕业论文荣誉。"
